Renaming Math.h -> MathUtils.h * Because on MacOS/XCode, the compiler confused Math.h with its own /usr/include/math.h and generated mysterious errors. * The compiler kept saying it couldn't find any of my wrapped std:: math functions. E.g.
In file included from unit_tests.cpp:13:
In file included from ./Math_tests.h:9:
../include/Core/math.h:152:17: error: reference to unresolved using declaration
  152 |     return std::sqrt(length_squared(x, y));